# Generated by Django 5.0.6 on 2024-07-10 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d")),
                ("description", models.TextField(blank=True)),
                ("is_mvp", models.BooleanField(default=False)),
                (
                    "hire_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
